### ISSUE TITLE
add method `.on()` to assign late events

### ISSUE THREAD

**Issue by phucbm** [viivue/easy-popup#17]
Same as https://github.com/viivue/easy-select/issues/15

Sometimes when the popup was initialized using HTML and then we want to assign an event, this method could help to assign events at any time.

Something like this.
```js
const instance = EasyPopup.get('my-popup');
instance.on('change', ()=>{
   // do something
});
```

**Comment by vishalpawarR** [comment]
Please can you give more input here and screenshot for better understanding of the problem?

**Comment by phucbm** [comment]
@vishalpawarR Thanks for reminding me. The description has been updated.
